### ISSUE TITLE
Please provide some docs for how to get started

### ISSUE THREAD

**Issue by JohnMcLear** [willwhitney/dc-ign#1]
I'd like to have a play but the docs are a little sparse in the README.

If you can put some instructions up I'd happily test them and help improve them :)

**Comment by mrkulk** [comment]
Yes, currently the basic usage is in the main.lua file. However, as you noticed it is sparse. My task for today was to update the readme and cleanup the starter code along with good comments. Thanks a lot for helping to test and improve.

**Comment by selbyk** [comment]
Yeah, I'd like to play around with this too.  Was just looking up cuda programming the other day trying to find a way to put my new gpu to use.

What is the preferred way to install the dependencies? Manually, OS's package manager, or LuaRocks?

I've only used Lua with Awesome WM so not that familiar with how it handles things

**Comment by willwhitney** [comment]
@selbyk LuaRocks is the way to go for all Torch packages.

NVidia requires a [signup](https://developer.nvidia.com/cuDNN) to download cuDNN, then you can install it directly from them.

I'm writing some better setup instructions right now — sorry they weren't clear before!

**Comment by soumith** [comment]
@willwhitney you can borrow some stuff from here: https://github.com/facebook/fbcunn/blob/master/INSTALL.md

**Comment by willwhitney** [comment]
@soumith ooh, those are nice. I'll just link to you guys!

**Comment by selbyk** [comment]
Hah, you shouldn't be required to do everything for us, Will.  I'll write up my setup process in case I run into any problems that may help someone else. 

And thanks @soumith, that looks like it'll be a big help =D

**Comment by willwhitney** [comment]
The instructions in the readme are now a good bit more detailed, too.
Thanks for testing this out!
