### ISSUE TITLE
LINK DOWNLOAD DATASET IS INVALID

### ISSUE THREAD

**Issue by VuHuy-cse-9** [willwhitney/dc-ign#10]
Hi, I cannot access your dataset via your download link.  
Please check it again.
Thanks very much.

**Comment by willwhitney** [comment]
Did you try the [backup Amazon S3 link](https://s3.amazonaws.com/willwhitney/dc-ign/dcign_facedataset_monovariant.zip) in the readme as well? That still seems to work for me.

**Comment by VuHuy-cse-9** [comment]
Thanks, It's work for me too.
