### ISSUE TITLE
pre-trained network is now missing

### ISSUE THREAD

**Issue by dribnet** [willwhitney/dc-ign#5]
Hi - the readme references download of a pre-trained network, but I think that is no longer available.

I actually found a cached copy of `dcign_sample_trained.zip` on my hard drive, so I no longer need to download it, but it seemed worth mentioning.

**Comment by willwhitney** [comment]
Whoops — things are a little disorganized here while we're getting a camera-ready version for NIPS. I'll put a link to that one back up shortly, and maybe a link to a better one later this month.

Thanks for the heads up!

**Comment by lopsided** [comment]
@willwhitney Link to dataset and pre trained net seem to be broken again

**Comment by willwhitney** [comment]
Ah, Dropbox got mad at us. I'll work on getting this back up in the next couple of days.

**Comment by willwhitney** [comment]
Dropbox links working again.

**Comment by lopsided** [comment]
:+1: Cheers!
