### ISSUE TITLE
Can't download the dataset from Dropbox

### ISSUE THREAD

**Issue by spk921** [willwhitney/dc-ign#8]
I was not able to download 3D face dataset on the dropbox.

Also, do you have the chair 3D dataset which you used on your paper? 

I know there is the repo for 3D chairs but wondering if you can share the processing code or datas.

**Comment by spk921** [comment]
I have download with amazon AWS.

However is there are color version of dataset? It only contains batch torch bin file.

**Comment by willwhitney** [comment]
There's not a color version, as all of our experiments were in black and white. However, you can download the [Basel face model](http://faces.cs.unibas.ch/bfm/main.php?nav=1-0&id=basel_face_model) and generate whatever data you need.
